### ISSUE TITLE
Linux can run 32bit applications on 64bit machines

### ISSUE THREAD

**Issue by bahhax404** [0xZ0F/Z0FCourse_ReverseEngineering#12]
in this [section](https://github.com/0xZ0F/Z0FCourse_ReverseEngineering/blob/master/0x100-BinaryBasics/0x104-ProgrammingLanguages.md) you mentioned that Linux is not backward compatible and that you cannot run 32bit applications on 64bit, but certainly you can when you install 32bit libs.
correct me if i'm wrong.
Good work though.

**Comment by 0xZ0F** [comment]
After doing a bit of research I'm pretty sure you're correct. Thank you for letting me know.
