### ISSUE TITLE
Link invalid in Chapter 3.2

### ISSUE THREAD

**Issue by UndefinedMuki** [0xZ0F/Z0FCourse_ReverseEngineering#19]
The following link returns a 404 error code

https://docs.microsoft.com/en-us/windows/desktop/api/winternl/ns-winternl-_peb

You probably meant
https://docs.microsoft.com/en-us/windows/desktop/api/winternl/ns-winternl-peb

**Comment by 0xZ0F** [comment]
Thank you for letting me know, it should be fixed now.
