### ISSUE TITLE
Possible mistake in chapter 3.2

### ISSUE THREAD

**Issue by entropidelic** [0xZ0F/Z0FCourse_ReverseEngineering#26]
First of all, thank you so much for writing this material, it is amazing.

I am a beginner with these low level topics so I might be wrong, but when I was reading the Stack explanation, these two parts seemed contradictory to me:
* _When data is pushed onto the stack, the stack grows up, towards lower memory addresses._

* _The stack pointer (RSP/ESP/SP) is used to keep track of the top of the stack and the base pointer (RBP/EBP/BP) is used to keep track of the base/bottom of the stack. This means that when data is pushed onto the stack, the stack pointer is increased since the stack grew towards higher addresses._ 

I think that the second quote should be,
> _The stack pointer (RSP/ESP/SP) is used to keep track of the top of the stack and the base pointer (RBP/EBP/BP) is used to keep track of the base/bottom of the stack. This means that when data is pushed onto the stack, the stack pointer is decreased since the stack grew towards lower addresses._

Let me know if I am getting it wrong :)

**Comment by 0xZ0F** [comment]
You're correct, that's definitely an issue. It's been fixed, thanks for letting me know!
